import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import PostButton from "@/components/postButton";
import React from "react";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-100 text-gray-600 relative`}
        >
        <div className={`flex justify-center items-center flex-col w-full box-border p-10 gap-5 h-screen`}>
            <div className={`flex justify-center items-center flex-col w-full shrink`}>
                {/*<h1 className={`font-black`}>一則貼文</h1>*/}
                <input type={`string`} placeholder={`請輸入文字房間ID`}
                       className={`text-center my-2 border-b border-gray-500 outline-none focus:border-amber-300 transition-all`}/>
                <button type={`submit`}
                        className={`cursor-pointer border border-gray-500 rounded-sm py-1 px-2 hover:bg-gray-500 hover:text-white`}>連線
                </button>
            </div>
            <main
                className={`flex-1 lg:w-[1024] w-full rounded-xl border border-white bg-white/30 relative overflow-y-auto`}>
                <div className={`w-full p-4 box-border`}>
                    {children}
                </div>
            </main>
            <PostButton/>
        </div>
        </body>
        </html>
    );
}
